# Generated by Django 3.2.3 on 2024-08-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categories', models.CharField(help_text='Укажите название категории', max_length=256, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catalog', models.CharField(help_text='Укажите название каталога', max_length=256, unique=True, verbose_name='Каталог')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'каталог',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(help_text='Введите наименование товара', max_length=256, unique=True, verbose_name='Наименование товара')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('price', models.FloatField(help_text='Укажите цену за единицу товара', max_length=6, verbose_name='Цена за единицу товара')),
                ('image', models.ImageField(help_text='Прикрепите фото товара', upload_to='product/', verbose_name='Изображение')),
                ('name_catalogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.directory')),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.categories')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='name_catalogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.directory'),
        ),
    ]
