# Generated by Django 3.2.3 on 2024-08-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_catalogs',
            field=models.ForeignKey(help_text='Выберите каталог', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reviews.directory', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_catalogs',
            field=models.ForeignKey(help_text='Выберите каталог', on_delete=django.db.models.deletion.CASCADE, to='reviews.directory', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='reviews.categories', verbose_name='Категория'),
        ),
    ]
